### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by wishx98** [mainaksingha01/APPLeNet#10]
Hi, I encountered an ValueError that I'm unable to resolve. Here's the specific error message I'm getting:

File "trainers/applenet.py", line 279, in forward
image_features, data = self.image_encoder(image.type(self.dtype))
ValueError: too many values to unpack (expected 2)

Could you help?

**Comment by mainaksingha01** [comment]
Fixed it. Check the clip folder. Thanks.

**Comment by sdracula** [comment]
Hi, I found that this problem had not been solved. The data cant be generated by pretrained CLIP image encoder in applenet now.

**Comment by sdracula** [comment]
This problem is still unsolved just because the clip folder lack the init file.

**Comment by mainaksingha01** [comment]
Hi, thanks for raising the concern. Please make sure to use the clip/model.py given in this repo, which is a modified version of original pretrained clip repo. Anyway, I have checked the code again, its working well.

**Comment by sdracula** [comment]
> Hi, thanks for raising the concern. Please make sure to use the clip/model.py given in this repo, which is a modified version of original pretrained clip repo. Anyway, I have checked the code again, its working well.

Thanks for your reply, its working well after I add the init.py just like your ODG-clip. Thanks again for your excellent work. Good luck to you.
