### ISSUE TITLE
RecursionError at the line : from dassl.engine import build_trainer 

### ISSUE THREAD

**Issue by Jarus77** [mainaksingha01/APPLeNet#13]
Details:

---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
Cell In[2], [line 1](vscode-notebook-cell:?execution_count=2&line=1)
----> from dassl.engine import build_trainer

from .build import build_evaluator, EVALUATOR_REGISTRY  # isort:skip
from .evaluator import EvaluatorBase, Classification
arg1 = dtype(arg1).type

if not issubclass_(arg2, generic):
    arg2 = dtype(arg2).type

RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by mainaksingha01** [comment]
Please send more information. It should not happen, please check any circular imports upon how you have downloaded the dassl folder.

**Comment by Jarus77** [comment]
Hi @mainaksingha01  thanks for your answer, I have placed the dassl folder in the parent directory itself, I have debugged line by line with debugger, and it seems to be circular import error, but i couldn't fix it. 

Below is the error in detail: 
{
	"name": "RecursionError",
	"message": "maximum recursion depth exceeded while calling a Python object",
	"stack": "---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 from dassl.engine import build_trainer

File ~/suraj/RepoAPPLeNet/dassl/engine/__init__.py:2
      1 from .build import TRAINER_REGISTRY, build_trainer  # isort:skip
----> 2 from .trainer import TrainerX, TrainerXU, TrainerBase, SimpleTrainer, SimpleNet  # isort:skip
      4 from .da import *
      5 from .dg import *

File ~/suraj/RepoAPPLeNet/dassl/engine/trainer.py:19
     13 from dassl.utils import (
     14     MetricMeter, AverageMeter, tolist_if_not, count_num_param, load_checkpoint,
     15     save_checkpoint, mkdir_if_missing, resume_from_checkpoint,
     16     load_pretrained_weights
     17 )
     18 from dassl.modeling import build_head, build_backbone
---> 19 from dassl.evaluation import build_evaluator
     20 import os
     22 class SimpleNet(nn.Module):

File ~/suraj/RepoAPPLeNet/dassl/evaluation/__init__.py:3
      1 from .build import build_evaluator, EVALUATOR_REGISTRY  # isort:skip
----> 3 from .evaluator import EvaluatorBase, Classification

File ~/suraj/RepoAPPLeNet/dassl/evaluation/evaluator.py:5
      3 from collections import OrderedDict, defaultdict
      4 import torch
----> 5 from sklearn.metrics import f1_score, confusion_matrix
      7 from .build import EVALUATOR_REGISTRY
     10 class EvaluatorBase:

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/sklearn/__init__.py:84
     70     # We are not importing the rest of scikit-learn during the build
     71     # process, as it may not be compiled yet
     72 else:
   (...)
     78     # later is linked to the OpenMP runtime to make it possible to introspect
     79     # it and importing it first would fail if the OpenMP dll cannot be found.
     80     from . import (
     81         __check_build,  # noqa: F401
     82         _distributor_init,  # noqa: F401
     83     )
---> 84     from .base import clone
     85     from .utils._show_versions import show_versions
     87     __all__ = [
     88         \"calibration\",
     89         \"cluster\",
   (...)
    130         \"show_versions\",
    131     ]

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/sklearn/base.py:19
     17 from ._config import config_context, get_config
     18 from .exceptions import InconsistentVersionWarning
---> 19 from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr
     20 from .utils._metadata_requests import _MetadataRequester, _routing_enabled
     21 from .utils._param_validation import validate_parameter_constraints

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/sklearn/utils/__init__.py:11
      9 from . import _joblib, metadata_routing
     10 from ._bunch import Bunch
---> 11 from ._chunking import gen_batches, gen_even_slices
     12 from ._estimator_html_repr import estimator_html_repr
     14 # Make _safe_indexing importable from here for backward compat as this particular
     15 # helper is considered semi-private and typically very useful for third-party
     16 # libraries that want to comply with scikit-learn's estimator API. In particular,
     17 # _safe_indexing was included in our public API documentation despite the leading
     18 # `_` in its name.

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/sklearn/utils/_chunking.py:8
      5 import numpy as np
      7 from .._config import get_config
----> 8 from ._param_validation import Interval, validate_params
     11 def chunk_generator(gen, chunksize):
     12     \"\"\"Chunk generator, ``gen`` into lists of length ``chunksize``. The last
     13     chunk may have a length less than ``chunksize``.\"\"\"

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/sklearn/utils/_param_validation.py:14
     11 from scipy.sparse import csr_matrix, issparse
     13 from .._config import config_context, get_config
---> 14 from .validation import _is_arraylike_not_scalar
     17 class InvalidParameterError(ValueError, TypeError):
     18     \"\"\"Custom exception to be raised when the parameter of a class/method/function
     19     does not have a valid type or value.
     20     \"\"\"

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/sklearn/utils/validation.py:26
     24 from .. import get_config as _get_config
     25 from ..exceptions import DataConversionWarning, NotFittedError, PositiveSpectrumWarning
---> 26 from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
     27 from ..utils.fixes import ComplexWarning, _preserve_dia_indices_dtype
     28 from ._isfinite import FiniteStatus, cy_isfinite

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/sklearn/utils/_array_api.py:11
      8 import scipy.special as special
     10 from .._config import get_config
---> 11 from .fixes import parse_version
     13 _NUMPY_NAMESPACE_NAMES = {\"numpy\", \"array_api_compat.numpy\"}
     16 def yield_namespaces(include_numpy_namespaces=True):

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/sklearn/utils/fixes.py:20
     18 import scipy
     19 import scipy.sparse.linalg
---> 20 import scipy.stats
     22 from ..externals._packaging.version import parse as parse_version
     23 from .parallel import _get_threadpool_controller

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/scipy/stats/__init__.py:610
      1 \"\"\"
      2 .. _statsrefmanual:
      3 
   (...)
    605 
    606 \"\"\"  # noqa: E501
    608 from ._warnings_errors import (ConstantInputWarning, NearConstantInputWarning,
    609                                DegenerateDataWarning, FitError)
--> 610 from ._stats_py import *
    611 from ._variation import variation
    612 from .distributions import *

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/scipy/stats/_stats_py.py:49
     46 # Import unused here but needs to stay until end of deprecation periode
     47 # See https://github.com/scipy/scipy/issues/15765#issuecomment-1875564522
     48 from scipy import linalg  # noqa: F401
---> 49 from . import distributions
     50 from . import _mstats_basic as mstats_basic
     52 from ._stats_mstats_common import _find_repeats, theilslopes, siegelslopes

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/scipy/stats/distributions.py:10
      1 #
      2 # Author:  Travis Oliphant  2002-2011 with contributions from
      3 #          SciPy Developers 2004-2011
   (...)
      6 #       instead of `git blame -Lxxx,+x`.
      7 #
      8 from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)  # noqa: F401
---> 10 from . import _continuous_distns
     11 from . import _discrete_distns
     13 from ._continuous_distns import *  # noqa: F403

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/scipy/stats/_continuous_distns.py:12
     10 import numpy as np
     11 from numpy.polynomial import Polynomial
---> 12 from scipy.interpolate import BSpline
     13 from scipy._lib.doccer import (extend_notes_in_docstring,
     14                                replace_notes_in_docstring,
     15                                inherit_docstring_from)
     16 from scipy._lib._ccallback import LowLevelCallable

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/scipy/interpolate/__init__.py:167
      1 \"\"\"
      2 ========================================
      3 Interpolation (:mod:`scipy.interpolate`)
   (...)
    165 (should not be used in new code).
    166 \"\"\"
--> 167 from ._interpolate import *
    168 from ._fitpack_py import *
    170 # New interface to fitpack library:

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/scipy/interpolate/_interpolate.py:12
      9 from scipy._lib._util import copy_if_needed
     10 from scipy.special import comb
---> 12 from . import _fitpack_py
     13 from ._polyint import _Interpolator1D
     14 from . import _ppoly

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/scipy/interpolate/_fitpack_py.py:8
      5 import numpy as np
      7 # These are in the API for fitpack even if not used in fitpack.py itself.
----> 8 from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
      9 from . import _fitpack_impl as _impl
     10 from ._bsplines import BSpline

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/scipy/interpolate/_fitpack_impl.py:103
     52 _iermess = {
     53     0: [\"The spline has a residual sum of squares fp such that \"
     54         \"abs(fp-s)/s<=0.001\", None],
   (...)
     68     'unknown': [\"An error occurred\", TypeError]
     69 }
     71 _iermess2 = {
     72     0: [\"The spline has a residual sum of squares fp such that \"
     73         \"abs(fp-s)/s<=0.001\", None],
   (...)
     99     'unknown': [\"An error occurred\", TypeError]
    100 }
    102 _parcur_cache = {'t': array([], float), 'wrk': array([], float),
--> 103                  'iwrk': array([], dfitpack_int), 'u': array([], float),
    104                  'ub': 0, 'ue': 1}
    107 def splprep(x, w=None, u=None, ub=None, ue=None, k=3, task=0, s=None, t=None,
    108             full_output=0, nest=None, per=0, quiet=1):
    109     # see the docstring of `_fitpack_py/splprep`
    110     if task <= 0:

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/_dtype.py:46, in __repr__(dtype)
     45 def __repr__(dtype):
---> 46     arg_str = _construction_repr(dtype, include_align=False)
     47     if dtype.isalignedstruct:
     48         arg_str = arg_str + \", align=True\"

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/_dtype.py:100, in _construction_repr(dtype, include_align, short)
     98     return _subarray_str(dtype)
     99 else:
--> 100     return _scalar_str(dtype, short=short)

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/_dtype.py:143, in _scalar_str(dtype, short)
    140 elif dtype.type == np.timedelta64:
    141     return \"'%sm8%s'\" % (byteorder, _datetime_metadata_str(dtype))
--> 143 elif np.issubdtype(dtype, np.number):
    144     # Short repr with endianness, like '<f8'
    145     if short or dtype.byteorder not in ('=', '|'):
    146         return \"'%s%c%d'\" % (byteorder, dtype.kind, dtype.itemsize)

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/numerictypes.py:417, in issubdtype(arg1, arg2)
    359 r\"\"\"
    360 Returns True if first argument is a typecode lower/equal in type hierarchy.
    361 
   (...)
    414 
    415 \"\"\"
    416 if not issubclass_(arg1, generic):
--> 417     arg1 = dtype(arg1).type
    418 if not issubclass_(arg2, generic):
    419     arg2 = dtype(arg2).type

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/_dtype.py:46, in __repr__(dtype)
     45 def __repr__(dtype):
---> 46     arg_str = _construction_repr(dtype, include_align=False)
     47     if dtype.isalignedstruct:
     48         arg_str = arg_str + \", align=True\"

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/_dtype.py:100, in _construction_repr(dtype, include_align, short)
     98     return _subarray_str(dtype)
     99 else:
--> 100     return _scalar_str(dtype, short=short)

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/_dtype.py:143, in _scalar_str(dtype, short)
    140 elif dtype.type == np.timedelta64:
    141     return \"'%sm8%s'\" % (byteorder, _datetime_metadata_str(dtype))
--> 143 elif np.issubdtype(dtype, np.number):
    144     # Short repr with endianness, like '<f8'
    145     if short or dtype.byteorder not in ('=', '|'):
    146         return \"'%s%c%d'\" % (byteorder, dtype.kind, dtype.itemsize)

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/numerictypes.py:417, in issubdtype(arg1, arg2)
    359 r\"\"\"
    360 Returns True if first argument is a typecode lower/equal in type hierarchy.
    361 
   (...)
    414 
    415 \"\"\"
    416 if not issubclass_(arg1, generic):
--> 417     arg1 = dtype(arg1).type
    418 if not issubclass_(arg2, generic):
    419     arg2 = dtype(arg2).type

    [... skipping similar frames: __repr__ at line 46 (466 times), _construction_repr at line 100 (466 times), _scalar_str at line 143 (466 times), issubdtype at line 417 (466 times)]

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/_dtype.py:46, in __repr__(dtype)
     45 def __repr__(dtype):
---> 46     arg_str = _construction_repr(dtype, include_align=False)
     47     if dtype.isalignedstruct:
     48         arg_str = arg_str + \", align=True\"

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/_dtype.py:100, in _construction_repr(dtype, include_align, short)
     98     return _subarray_str(dtype)
     99 else:
--> 100     return _scalar_str(dtype, short=short)

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/_dtype.py:143, in _scalar_str(dtype, short)
    140 elif dtype.type == np.timedelta64:
    141     return \"'%sm8%s'\" % (byteorder, _datetime_metadata_str(dtype))
--> 143 elif np.issubdtype(dtype, np.number):
    144     # Short repr with endianness, like '<f8'
    145     if short or dtype.byteorder not in ('=', '|'):
    146         return \"'%s%c%d'\" % (byteorder, dtype.kind, dtype.itemsize)

File ~/anaconda3/envs/cocoop/lib/python3.11/site-packages/numpy/core/numerictypes.py:417, in issubdtype(arg1, arg2)
    359 r\"\"\"
    360 Returns True if first argument is a typecode lower/equal in type hierarchy.
    361 
   (...)
    414 
    415 \"\"\"
    416 if not issubclass_(arg1, generic):
--> 417     arg1 = dtype(arg1).type
    418 if not issubclass_(arg2, generic):
    419     arg2 = dtype(arg2).type

RecursionError: maximum recursion depth exceeded while calling a Python object"
}

**Comment by Jarus77** [comment]
I have solved the issue. Actually scipy and sklearn were causing circular import error, cause i was using older version of them .

Issues got resolved by:
`pip install --upgrade scipy scikit-learn numpy
`
